//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cagdasotomasyon_v1._0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cagdasotomasyon_v1._0.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string adı {
            get {
                return ResourceManager.GetString("adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış.
        /// </summary>
        internal static string alıs {
            get {
                return ResourceManager.GetString("alıs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara:.
        /// </summary>
        internal static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azalan Ürünler.
        /// </summary>
        internal static string azalan_urunler {
            get {
                return ResourceManager.GetString("azalan urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çağdaş Otomasyon.
        /// </summary>
        internal static string cagdas_otomasyon {
            get {
                return ResourceManager.GetString("cagdas_otomasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo.
        /// </summary>
        internal static string depo {
            get {
                return ResourceManager.GetString("depo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depolar.
        /// </summary>
        internal static string depolar {
            get {
                return ResourceManager.GetString("depolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        internal static string eposta {
            get {
                return ResourceManager.GetString("eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string giriş {
            get {
                return ResourceManager.GetString("giriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string gönder {
            get {
                return ResourceManager.GetString("gönder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string güncelle {
            get {
                return ResourceManager.GetString("güncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hatırlatma.
        /// </summary>
        internal static string hatırlatma {
            get {
                return ResourceManager.GetString("hatırlatma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin,.
        /// </summary>
        internal static string hosgeldin {
            get {
                return ResourceManager.GetString("hosgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Miktar 50 den az kalan ürünler Kırmızı ile işaretllenir.
        /// </summary>
        internal static string işaret_kırmızı {
            get {
                return ResourceManager.GetString("işaret_kırmızı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Miktar 200 den az kalan ürünler Sarı ile işaretllenir.
        /// </summary>
        internal static string işaret_sarı {
            get {
                return ResourceManager.GetString("işaret_sarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        internal static string Kullanıcı {
            get {
                return ResourceManager.GetString("Kullanıcı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        internal static string kullanici_adi {
            get {
                return ResourceManager.GetString("kullanici_adi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        internal static string kullanıcilar {
            get {
                return ResourceManager.GetString("kullanıcilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string lokasyon {
            get {
                return ResourceManager.GetString("lokasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktarı.
        /// </summary>
        internal static string miktar {
            get {
                return ResourceManager.GetString("miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girmiş Olduğunuz Bilgiler Uyuşuyor Şifreniz Mail Olarak Gönderildi.
        /// </summary>
        internal static string onay_text {
            get {
                return ResourceManager.GetString("onay_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girmiş Olduğunuz Bilgiler Uyuşmuyor.
        /// </summary>
        internal static string red_text {
            get {
                return ResourceManager.GetString("red_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        internal static string satıs {
            get {
                return ResourceManager.GetString("satıs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        internal static string sehir {
            get {
                return ResourceManager.GetString("sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre.
        /// </summary>
        internal static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifremi unuttum.
        /// </summary>
        internal static string sifre_unut {
            get {
                return ResourceManager.GetString("sifre_unut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreni öğrenebilmek için mail adresine şifreni gönder.
        /// </summary>
        internal static string sifre_unut_baslik {
            get {
                return ResourceManager.GetString("sifre_unut_baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        internal static string şifremiunuttum {
            get {
                return ResourceManager.GetString("şifremiunuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu.
        /// </summary>
        internal static string sorumlu {
            get {
                return ResourceManager.GetString("sorumlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        internal static string soyadı {
            get {
                return ResourceManager.GetString("soyadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        internal static string urun {
            get {
                return ResourceManager.GetString("urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        internal static string urunler {
            get {
                return ResourceManager.GetString("urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string yenile {
            get {
                return ResourceManager.GetString("yenile", resourceCulture);
            }
        }
    }
}
